In [ ]:
import os
import re
import pandas as pd
import rispy

# Set the root directory containing all the subfolders
root_dir = r'C:\Users\yourpathto\ArticlesData'   # <-- Replace this with your actual path


# Initialize a list to collect all entries
all_entries = []

# Regex pattern to extract Q and T from folder name
folder_pattern = re.compile(r'Q(\d+)xT(\d+)\s+(Scopus|DTU FindIt Eng|Google Scholar|DTU FindIt Esp)')
# Walk through each subfolder
for folder_name in os.listdir(root_dir):
    match = folder_pattern.match(folder_name)
    if not match:
        continue  # Skip folders not matching the expected pattern

    Q_val, T_val, database = match.groups()
    folder_path = os.path.join(root_dir, folder_name)

    # Find the .ris file in the folder
    ris_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.ris')]
    if not ris_files:
        continue  # Skip if no RIS file is found

    ris_path = os.path.join(folder_path, ris_files[0])
    
    # Parse RIS file
    with open(ris_path, 'r', encoding='utf-8') as ris_file:
        entries = rispy.load(ris_file)

        for entry in entries:
            # Add Q, T, and database to each entry
            entry['Q'] = int(Q_val)
            entry['T'] = int(T_val)
            entry['Database'] = database
            # Check for journal name using multiple possible tags
            journal = (
                entry.get('secondary_title') or  # T2 tag in RIS (standard for journal names)
                entry.get('journal_name') or     # Backup field
                entry.get('alternate_title3') or # Another possible field
                ''  # Default empty string if none found
            )
            #Save the abstract too in a new field
            entry['abstract_text'] = entry.get('abstract', '')

            # If a journal name is found, clean it up
            entry['journal_name'] = journal.strip() if journal else ''
            all_entries.append(entry)

# Convert to DataFrame
df = pd.DataFrame(all_entries)

# Rename or select useful columns if needed
columns_of_interest = {
    'title': 'Title',
    'authors': 'Authors',
    'year': 'Year',
    'journal_name': 'Journal',
    'doi': 'DOI',
    'url': 'URL',
    'publisher': 'Publisher',
    'type_of_reference': 'ReferenceType',
    'Database': 'Database',
    'Q': 'Q',
    'T': 'T',
    'abstract_text': 'Abstract'
}

# Filter and rename only those columns present in the data
final_columns = {k: v for k, v in columns_of_interest.items() if k in df.columns}
df = df[list(final_columns.keys())].rename(columns=final_columns)

def filter_by_year(df, min_year):
    # Ensure 'year' is numeric
    df['year'] = pd.to_numeric(df['Year'], errors='coerce')
    # Keep rows where year is NaN (missing) OR year >= min_year
    filtered_df = df[df['year'].isna() | (df['year'] >= min_year)].copy()
    return filtered_df.reset_index(drop=True)

df = filter_by_year(df, 2010)
# Show result
df
# Optional: Export to CSV
# df.to_csv("literature_review_data.csv", index=False)

,Title,Authors,Year,Journal,DOI,Publisher,ReferenceType,Database,Q,T,Abstract,year
0,Training quantum Boltzmann machines with the β...,"[Huijgen, Onno, Coopmans, Luuk, Najafi, Peyman...",2024,Machine Learning: Science and Technology,10.1088/2632-2153/ad370f,Institute of Physics,JOUR,DTU FindIt Eng,11,5,The quantum Boltzmann machine (QBM) is a gener...,2024.0
1,Andreev non-Hermitian Hamiltonian for open Jos...,"[Capecelatro, R., Marciani, M., Campagnano, G....",2025,Physical Review B,10.1103/PhysRevB.111.064517,American Physical Society,JOUR,DTU FindIt Eng,1,1,We investigate the transport properties of ope...,2025.0
2,Anti-scarring from eigenstate stacking in a ch...,"[Lu, Zhongling, Graf, Anton M., Heller, Eric J...",2025,,NaN,NaN,JOUR,DTU FindIt Eng,1,1,The early-time dynamics of many-body quantum c...,2025.0
3,Apparent teleportation of indistinguishable pa...,"[Gazdzicki, Marek, Kikola, Daniel, Pidhurskyi,...",2025,,NaN,NaN,JOUR,DTU FindIt Eng,1,1,"Teleportation, introduced in science fiction l...",2025.0
4,Beyond nearest-neighbor universality of spectr...,"[Kundu, Debojyoti, Kumar, Santosh, Sen Gupta, ...",2025,Chaos,10.1063/5.0234333,AIP Publishing LLC,JOUR,DTU FindIt Eng,1,1,Discerning chaos in quantum systems is an impo...,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...
22499,2013 2nd International Conference on Civil Eng...,NaN,2014,Advanced Materials Research,NaN,NaN,JOUR,Scopus,7,9,,2014.0
22500,"15th Metaheuristics International Conference, ...",NaN,2024,Lecture Notes in Computer Science (including s...,NaN,NaN,JOUR,Scopus,7,9,,2024.0
22501,"15th Metaheuristics International Conference, ...",NaN,2024,Lecture Notes in Computer Science (including s...,NaN,NaN,JOUR,Scopus,7,9,,2024.0
22502,3rd International Conference on Futuristic Tre...,NaN,2021,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,7,9,,2021.0
22503,3rd International Conference on Futuristic Tre...,NaN,2021,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,7,9,,2021.0

In [2]:
database_counts = df['Database'].value_counts()

# Print the result
print(database_counts)
#print total number of entries
print(f'Total number of entries: {len(df)}')

Database
Scopus            14996
DTU FindIt Eng     7005
Google Scholar      469
DTU FindIt Esp       34
Name: count, dtype: int64
Total number of entries: 22504

In [3]:
def deduplicate_articles_with_database_priority(df):
    # Define database priority (lower number = higher priority)
    db_priority = {
        'Google Scholar': 1,
        'Scopus': 2,
        'DTU Find It Esp': 3,
        'DTU Find It Eng': 4
    }

    # Assign numeric Q and T for sorting
    df['db_priority'] = df['Database'].map(db_priority)

    # Create deduplication keys
    df['dedup_key'] = df['DOI'].fillna('').str.lower().str.strip()
    df['alt_key'] = df['Title'].str.lower().str.strip() + '_' + df['Year'].astype(str)

    # Sort by deduplication priority: Higher Q, then T, then better database
    df = df.sort_values(by=['dedup_key', 'alt_key', 'Q', 'T', 'db_priority'], ascending=[True, True, False, False, True])

    # Use groupby to keep the first occurrence of each duplicate key
    seen_keys = set()
    keep_rows = []

    for idx, row in df.iterrows():
        key = row['dedup_key'] if row['dedup_key'] else row['alt_key']
        if key not in seen_keys:
            seen_keys.add(key)
            keep_rows.append(idx)

    deduped_df = df.loc[keep_rows].drop(columns=['db_priority', 'dedup_key', 'alt_key']).reset_index(drop=True)
    return deduped_df

In [4]:
deduped_df = deduplicate_articles_with_database_priority(df)

In [5]:
def filter_by_year(df, min_year):
    # Ensure 'year' is numeric
    df['year'] = pd.to_numeric(df['Year'], errors='coerce')
    # Keep rows where year is NaN (missing) OR year >= min_year
    filtered_df = df[df['year'].isna() | (df['year'] >= min_year)].copy()
    return filtered_df.reset_index(drop=True)

filtered_df = filter_by_year(deduped_df, 2010)
filtered_df

,Title,Authors,Year,Journal,DOI,Publisher,ReferenceType,Database,Q,T,Abstract,year
0,$\mathrm{\Lambda_{c}^{+}}$ baryon production m...,"[Norman, Jaime]",2018,,NaN,NaN,JOUR,DTU FindIt Eng,1,1,"Quantum chromodynamics, the quantum field theo...",2018.0
1,10th EAI International Conference on Industria...,NaN,2024,Lecture Notes of the Institute for Computer Sc...,NaN,NaN,JOUR,Scopus,7,7,The proceedings contain 18 papers. The special...,2024.0
2,10th International Conference on Emerging Ubiq...,NaN,2019,Procedia Computer Science,NaN,NaN,CONF,Scopus,7,6,The proceedings contain 126 papers. The topics...,2019.0
3,10th International Conference on Monte Carlo a...,NaN,2013,Springer Proceedings in Mathematics and Statis...,NaN,NaN,CONF,Scopus,1,6,The proceedings contain 34 papers. The special...,2013.0
4,10th International Symposium on Intelligence C...,NaN,2019,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,1,6,The proceedings contain 32 papers. The special...,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13463,Large-scale mesoscopic transport in nanostruct...,"[Hai-Jing, Zhang]",2013,Wuli,10.7693/wl201.30701,NaN,JOUR,DTU FindIt Eng,1,1,,2013.0
13464,Mechanistic pathways of mercury removal fromth...,"[Silva, P.J., Rodrigues, V.]",2015,PeerJ,10.7717/peerj.1127,NaN,JOUR,Scopus,1,5,Bacterial populations present in Hg-rich envir...,2015.0
13465,"Pharmacoscreening, molecular dynamics, and qua...","[Janakiraman, V., Sudhan, M., Wani, A., Ahmad,...",2023,PeerJ,10.7717/peerj.16481,NaN,JOUR,Scopus,1,6,"Background. Exosomes, microvesicles, carry and...",2023.0
13466,Sub-celluiar localization of PELPK1 in Arabido...,"[Rashid, A.]",2014,Molekuliarnaia biologiia,10.7868/s0026898414020165,NaN,JOUR,Scopus,1,1,"PELPK1, a novel Arabidopsis thaliana gene was ...",2014.0
13467,Molecular Dynamics Simulation of the Electroch...,"[Anant Babu, Marahatta]",2023,Asian Journal of Chemical Sciences,10.9734/ajocs/2023/v13i1229,Sciencedomain International,JOUR,DTU FindIt Eng,1,5,Being the most potential battery candidate for...,2023.0

In [6]:
import re
import pandas as pd

def find_paper_by_title_loose(df, title_query):
    """
    Loosely compare all titles to a query and rank by keyword overlap.
    Prints all entries, sorted by relevance.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame produced by your existing code
    title_query : str
        Full paper title or a descriptive fragment

    Returns
    -------
    pd.DataFrame
        All rows with a MatchScore column
    """
    if 'Title' not in df.columns:
        raise ValueError("Column 'Title' not found in DataFrame.")

    # Normalize function
    def normalize(text):
        text = str(text).lower()
        text = re.sub(r'[^a-z0-9\s]', ' ', text)
        return re.sub(r'\s+', ' ', text).strip()

    query_words = set(normalize(title_query).split())

    def match_score(title):
        if pd.isna(title):
            return 0
        title_words = set(normalize(title).split())
        return len(query_words & title_words)

    result = df.copy()
    result['MatchScore'] = result['Title'].apply(match_score)

    return result[
        ['MatchScore', 'Title', 'Q', 'T', 'Database', 'Year', 'Journal']
    ].sort_values('MatchScore', ascending=False)

In [7]:
def filter_out_by_keywords(df, keywords, title_col, verbose=True):
    """Filter out articles whose titles contain specific keywords.
    
    Args:
        df (DataFrame): Input DataFrame containing article information
        keywords (list): List of keywords to filter out
        title_col (str): Column name containing article titles
        verbose (bool): Whether to print statistics about filtering
        
    Returns:
        DataFrame: Filtered DataFrame with matching articles removed
    """
    if df.empty or not keywords:
        return df
    
    # Initial count
    initial_count = len(df)
    
    # Combine keywords into a single regex pattern (case-insensitive)
    pattern = re.compile('|'.join(re.escape(k) for k in keywords), flags=re.IGNORECASE)
    
    # Create a boolean mask for rows to keep (those NOT containing keywords)
    mask = ~df[title_col].fillna('').str.contains(pattern, na=False, regex=True)
    
    # Apply the mask
    filtered_df = df[mask].copy().reset_index(drop=True)
    
    # Report statistics if verbose
    if verbose:
        excluded_count = initial_count - len(filtered_df)
        print(f"Filtered out {excluded_count} articles ({excluded_count/initial_count*100:.1f}%) "
              f"containing these keywords in titles: {', '.join(keywords)}")
        
        # Find some examples of excluded articles for verification
        if excluded_count > 0:
            excluded_df = df[~mask]
            print("\nExamples of excluded articles:")
            #for _, row in excluded_df.head(90).iterrows():
            for i, (_, row) in enumerate(excluded_df.head(90).iterrows()):
                title = row[title_col]
                matching_keywords = [k for k in keywords if re.search(k, title, re.IGNORECASE)]
                print(f"- '{title}' (matched: {', '.join(matching_keywords)})")
    
    return filtered_df

In [8]:
keywords_to_exclude = ['chem', 'metal', 'molec', 'bio', 'cond', 'cataly', 'material', 'solid', 'spectro', 'fluor', 'pharma']
filtered_df = filter_out_by_keywords(filtered_df, keywords_to_exclude, 'Journal', verbose=True)
filtered_df

Filtered out 4275 articles (31.7%) containing these keywords in titles: chem, metal, molec, bio, cond, cataly, material, solid, spectro, fluor, pharma

Examples of excluded articles:
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including Subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Conference on Optoelectronic and Microelectronic Materials and Devices, Proceedings, COMMAD' (matched: material)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'Advanced Materials Research' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Solid State Phenomena' (matched: solid)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Advanced Materials Research' (matched: material)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Advanced Materials Research' (matched: material)
- 'Materials Science Forum' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Advanced Materials Research' (matched: material)
- 'Advanced Materials Research' (matched: material)
- 'Applied Mechanics and Materials' (matched: material)
- 'Lecture Notes in Bioengineering' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Advanced Materials Research' (matched: material)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- '2011 International Conference on Compound Semiconductor Manufacturing Technology, CS MANTECH 2011' (matched: cond)
- 'International Conference on Metamaterials, Photonic Crystals and Plasmonics' (matched: material)
- 'Optoelectronics and Advanced Materials, Rapid Communications' (matched: material)
- 'Frontiers in Medicinal Chemistry' (matched: chem)
- 'TechConnect Briefs 2018 - Advanced Materials' (matched: material)
- 'Journal of Materials and Engineering Structures' (matched: material)
- 'TechConnect Briefs 2018 - Advanced Materials' (matched: material)
- '25th Technical Conference of the American Society for Composites and 14th US-Japan Conference on Composite Materials 2010' (matched: material)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'International Conference on Simulation of Semiconductor Processes and Devices, SISPAD' (matched: cond)
- 'Chemicke Listy' (matched: chem)
- 'Chemical Engineers in Medicine 2017 - Topical Conference at the 2017 AIChE Annual Meeting' (matched: chem)
- 'Journal of Optoelectronics and Advanced Materials' (matched: material)
- 'Materials Today-proceedings' (matched: material)
- 'International Journal of ChemTech Research' (matched: chem)
- 'Research Journal of Pharmaceutical, Biological and Chemical Sciences' (matched: chem, bio, pharma)
- 'Lecture Notes in Computer Science (including subseries Lecture Notes in Artificial Intelligence and Lecture Notes in Bioinformatics)' (matched: bio)
- 'Journal of the Chemical Society of Pakistan' (matched: chem)
- 'Guti Dianzixue Yanjiu Yu Jinzhan/Research and Progress of Solid State Electronics' (matched: solid)

,Title,Authors,Year,Journal,DOI,Publisher,ReferenceType,Database,Q,T,Abstract,year
0,$\mathrm{\Lambda_{c}^{+}}$ baryon production m...,"[Norman, Jaime]",2018,,NaN,NaN,JOUR,DTU FindIt Eng,1,1,"Quantum chromodynamics, the quantum field theo...",2018.0
1,10th EAI International Conference on Industria...,NaN,2024,Lecture Notes of the Institute for Computer Sc...,NaN,NaN,JOUR,Scopus,7,7,The proceedings contain 18 papers. The special...,2024.0
2,10th International Conference on Emerging Ubiq...,NaN,2019,Procedia Computer Science,NaN,NaN,CONF,Scopus,7,6,The proceedings contain 126 papers. The topics...,2019.0
3,10th International Conference on Monte Carlo a...,NaN,2013,Springer Proceedings in Mathematics and Statis...,NaN,NaN,CONF,Scopus,1,6,The proceedings contain 34 papers. The special...,2013.0
4,10th International Symposium on Intelligence C...,NaN,2019,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,1,6,The proceedings contain 32 papers. The special...,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9188,Calculation of Rate Coefficients for Unsymmetr...,"[Yin, G., You, J., Hu, E., Huang, Z.]",2024,Hsi-An Chiao Tung Ta Hsueh/Journal of Xi'an Ji...,10.7652/xjtuxb202412020,NaN,JOUR,Scopus,1,5,To address the issue of inaccuracies in the ki...,2024.0
9189,Simulation of vehicle distribution path optimi...,"[Ding, Y.]",2021,Shenyang Gongye Daxue Xuebao/Journal of Shenya...,10.7688/j.issn.1000-1646.2021.03.13,NaN,JOUR,Scopus,1,6,In view of the problems of low load rate of si...,2021.0
9190,Large-scale mesoscopic transport in nanostruct...,"[Hai-Jing, Zhang]",2013,Wuli,10.7693/wl201.30701,NaN,JOUR,DTU FindIt Eng,1,1,,2013.0
9191,Mechanistic pathways of mercury removal fromth...,"[Silva, P.J., Rodrigues, V.]",2015,PeerJ,10.7717/peerj.1127,NaN,JOUR,Scopus,1,5,Bacterial populations present in Hg-rich envir...,2015.0
9192,"Pharmacoscreening, molecular dynamics, and qua...","[Janakiraman, V., Sudhan, M., Wani, A., Ahmad,...",2023,PeerJ,10.7717/peerj.16481,NaN,JOUR,Scopus,1,6,"Background. Exosomes, microvesicles, carry and...",2023.0

In [9]:
# Example of using the title keyword filter
title_keywords_to_exclude = ['chemi','metal', 'cataly', ' ion', '-ion', 'virus','molec', 'bio', 'nano', 'crystal', 'atom', 'proton', 'protein', 'organic', \
                            'organom', 'photon', 'laser', 'transistor', 'josephson', 'superconduct', 'der Waals', 'quantum dot', 'graphen', 'graphit', 'cancer', 'silicon', \
                            'semiconduct', 'spectroscop', 'benzene', 'vinyl', 'ethyl', 'sulfuri', 'DNA', 'alcohol', 'polymer', 'fluor', 'chlorophyl', 'caroten', 'bacter', \
                            'microbi', 'mosfet', 'oxid', 'optic', 'chromat', 'dipole', 'Einstein', 'aromat', ' Si ', 'TiO2', 'InGaN', 'indium', 'AlxGa1', 'epitaxy',\
                            'acid', 'solvent', 'myosin', 'nucleotid', 'ribonucle', 'Cs2Te', ' opto', 'substrate', 'MOSHEMT', 'photodetect', 'nitrid', 'gallium','Ti3C2T','zinc',\
                            'ZnTeSe', 'quantum-dot', 'phospho', 'phenyl', 'Chlor', 'MoTe2', 'therapy', 'selenium', 'dosimetry', 'patient', 'sound', 'Fermi','Weyl', 'Dirac', \
                            'hydrogen', 'oxyge', 'phonon', 'hydrocarbo', 'lithium', 'neutron', 'supernov', 'sodium', 'majorana', 'Bogoliubov', 'ferromagn','cardio', ' gluon ', \
                            'neutrino', 'dark matter', 'meson', 'parton','quark', 'baryon', 'InGaAs', 'Rb2Sn', 'InAsSb','thiophene','perovskite', 'copper', 'sulfide', 'tungsten',\
                            'GaN-', 'AlGaN', 'Cathodo', 'SrTiO3', 'LaAlO3', 'photosynth', 'electrode', 'planet', 'pharma', 'medical imag', 'exciton', 'cosmo', 'ethanol', 'drug',\
                            'metaboli', 'chiral', 'CuO/ZnO', 'naphthal', 'pentadi', 'black hole', '/GaN', 'GaN/'] #Do not exclude BOSON

# Assuming is your dataframe with articles
filtered_df = filter_out_by_keywords(filtered_df, title_keywords_to_exclude, 'Title', verbose=True)
filtered_df

Filtered out 5093 articles (55.4%) containing these keywords in titles: chemi, metal, cataly,  ion, -ion, virus, molec, bio, nano, crystal, atom, proton, protein, organic, organom, photon, laser, transistor, josephson, superconduct, der Waals, quantum dot, graphen, graphit, cancer, silicon, semiconduct, spectroscop, benzene, vinyl, ethyl, sulfuri, DNA, alcohol, polymer, fluor, chlorophyl, caroten, bacter, microbi, mosfet, oxid, optic, chromat, dipole, Einstein, aromat,  Si , TiO2, InGaN, indium, AlxGa1, epitaxy, acid, solvent, myosin, nucleotid, ribonucle, Cs2Te,  opto, substrate, MOSHEMT, photodetect, nitrid, gallium, Ti3C2T, zinc, ZnTeSe, quantum-dot, phospho, phenyl, Chlor, MoTe2, therapy, selenium, dosimetry, patient, sound, Fermi, Weyl, Dirac, hydrogen, oxyge, phonon, hydrocarbo, lithium, neutron, supernov, sodium, majorana, Bogoliubov, ferromagn, cardio,  gluon , neutrino, dark matter, meson, parton, quark, baryon, InGaAs, Rb2Sn, InAsSb, thiophene, perovskite, copper, sulfide, tungsten, GaN-, AlGaN, Cathodo, SrTiO3, LaAlO3, photosynth, electrode, planet, pharma, medical imag, exciton, cosmo, ethanol, drug, metaboli, chiral, CuO/ZnO, naphthal, pentadi, black hole, /GaN, GaN/

Examples of excluded articles:
- '$\mathrm{\Lambda_{c}^{+}}$ baryon production measurements with the ALICE experiment at the LHC' (matched: baryon)
- '12th International Conference on Numerical Simulation of Optoelectronic Devices, NUSOD 2012' (matched:  opto)
- '14th International Photonics and Optoelectronics Meetings, POEM 2022' (matched: photon,  opto)
- '2012 International Conference on Optical Engineering, ICOE 2012' (matched: optic)
- '2020 Photonics North, PN 2020' (matched: photon)
- '2021 Asia Communications and Photonics Conference, ACP 2021 - Proceedings' (matched: photon)
- '2nd International Conference on Micro and Nanoelectronics Devices, Circuits and Systems, MNDCS 2022' (matched: nano)
- '2nd Workshop on Theory, Modelling and Computational Methods for Semiconductors' (matched: semiconduct)
- '3rd International Summer School on Nanotechnology: From Fundamental Research to Innovations and 2nd International Conference NANO 2014' (matched: nano)
- '4th International Conference on Optical and Wireless Technologies, OWT 2020' (matched: optic)
- '4th Workshop on Theory, Modelling and Computational Methods for Semiconductors, TMCS 2014' (matched: semiconduct)
- '50th Annual Convention of Computer Society of India: Silicon Photonics and High Performance Computing, CSI 2015' (matched: photon, silicon)
- '5th International Conference on Nanotechnologies and Biomedical Engineering, ICNBME 2021' (matched: bio, nano)
- '6th International Research and Practice Conference on Nanotechnology and Nanomaterials, NANO 2018' (matched: nano)
- '8th International Conference on High-Capacity Optical Networks and Emerging Technologies, HONET 2011' (matched: optic)
- 'A 3D simulation comparison of carrier transport in green and blue c-plane multi-quantum well nitride light emitting diodes' (matched: nitrid)
- 'A composite electrodynamic mechanism to reconcile spatiotemporally resolved exciton transport in quantum dot superlattices [arXiv]' (matched: quantum dot, exciton)
- 'A derivation of the conditions under which bosonic operators exactly capture fermionic structure and dynamics [arXiv]' (matched: Fermi)
- 'A fast time domain travelling wave method for simulation of quantum dot lasers and amplifiers' (matched: laser, quantum dot)
- 'A Fermi Surface Descriptor Quantifying the Correlations between Anomalous Hall Effect and Fermi Surface Geometry' (matched: Fermi)
- 'A Flexibility and Accuracy Comparison Study of Different Current-Voltage Equations for Double-Gate Nano-MOSFET by Simulation and Theory' (matched: nano, mosfet)
- 'A fully anlytical model for carbon nanotube FETs including quantum capacitances and electrostatics' (matched: nano)
- 'A group-theoretic approach to the origin of chirality-induced spin selectivity in non-magnetic molecular junctions [arXiv]' (matched: molec, chiral)
- 'A high finesse bow-tie cavity for strong atom-photon coupling in Rydberg arrays [arXiv]' (matched: atom, photon)
- 'A hydrodynamical description for magneto-transport in the strange metal phase of cuprates' (matched: metal)
- 'A Landauer Formula for Bioelectronic Applications [arXiv]' (matched: bio)
- 'A Landauer Formula for Bioelectronic Applications' (matched: bio)
- 'A Model of Charge-Transfer Excitons: Diffusion, Spin Dynamics, and Magnetic Field Effects' (matched: exciton)
- 'A Molecular Perspective of Exciton Condensation from Particle-hole Reduced Density Matrices' (matched: molec, exciton)
- 'A Predictive First-Principles Framework of Chiral Charge Density Waves' (matched: chiral)
- 'A quantum bio-parasitic genetic algorithm for solving a hybrid scheduling problem of flow shop and two-stage transportation' (matched: bio)
- 'A quantum processor based on coherent transport of entangled atom arrays' (matched: atom)
- 'A self-aligning recirculated crossed optical dipole trap for lithium atoms' (matched: atom, optic, dipole, lithium)
- 'A Validated Method for Predicting Small Molecule Ionization Sites using Gibb's Free Energies' (matched:  ion, molec)
- 'A vertical gate-defined double quantum dot in a strained germanium double quantum well' (matched: quantum dot)
- 'Ab-initio electronic transport in narrow gap semiconductors using the Wigner distribution [arXiv]' (matched: semiconduct)
- 'Ab-initio electronic transport in narrow gap semiconductors using the Wigner distribution' (matched: semiconduct)
- 'Absorptive pinhole collimators for ballistic Dirac fermions in graphene [arXiv]' (matched: graphen, Fermi, Dirac)
- 'Accounting For Quantum Phenomena In Classical Molecular Dynamics Simulations At Cryogenic Temperatures: Diffraction And The Feynman-Hibbs Correction [arXiv]' (matched: molec)
- 'Advances in Silicon and Lithium Niobate Photonic Devices for Quantum Applications: Design, Fabrication, and Experimental Studies' (matched: photon, silicon, lithium)
- 'Advection Algorithms for Quantum Neutrino Moment Transport' (matched: neutrino)
- 'Algorithms for embedding quantum-dot cellular automata networks onto a quantum annealing processor' (matched: quantum-dot)
- 'Aluminum nanoparticles for efficient light-trapping in plasmonic gallium arsenide solar cells' (matched: nano, gallium)
- 'Amorphous solids as fuzzy crystals: A Debye-like theory of low-temperature specific heat' (matched: crystal)
- 'An adaptive-mesh-refinement based computational tool for simulating catalysis at mesoscale' (matched: cataly)
- 'An Approach to Use Depletion Charges for Modifying Band Profiles for Field-Effect Transistors' (matched: transistor)
- 'An Architecture for Improved Surface Code Connectivity in Neutral Atoms' (matched: atom)
- 'An atomistic model of field-induced resistive switching in valence change memory [arXiv]' (matched: atom)
- 'An Atomistic Model of Field-Induced Resistive Switching in Valence Change Memory' (matched: atom)
- 'An attack impairment-aware multicast routing algorithm based on hyper-domain graph model in multi-domain optical network' (matched: optic)
- 'Analysis of ballistic transport and resonance in the $\alpha$-Fermi-Pasta-Ulam-Tsingou model' (matched: Fermi)
- 'Analysis of non-uniform doping in silicon solar cell and optimization using PC1D' (matched: silicon)
- 'Anomalous chiral transport in heavy ion collisions from anomalous-viscous fluid dynamics' (matched:  ion, chiral)
- 'Anomalous Interlayer Exciton Diffusion in Twist-Angle-Dependent Moir\'{e} Potentials of WS$_2$-WSe$_2$ Heterobilayers' (matched: exciton)
- 'Anomalous Interlayer Exciton Diffusion in Twist-Angle-Dependent Moire Potentials of WS2-WSe2 Heterobilayers [arXiv]' (matched: exciton)
- 'Anomalous interlayer exciton diffusion in twist-angle-dependent moiré potentials of WS2-WSe2 heterobilayers' (matched: exciton)
- 'Anomalous spin diffusion in one-dimensional antiferromagnets [arXiv]' (matched: ferromagn)
- 'Application of computational quantum chemistry to nanotechnological problems' (matched: chemi, nano)
- 'Assessment of Monolayer Black Arsenic Metal-Oxide-Semiconductor Field Effect Transistors through Valley-Resolved Ab-Initio Quantum Transport Simulation' (matched: metal, transistor, semiconduct, oxid)
- 'Atomistic modeling and quantum transport simulation of nano-scaled devices based on the density functional theory Hamiltonian' (matched: nano, atom)
- 'Atomistic modeling and simulation of long-term transport phenomena in nanomaterials' (matched: nano, atom)
- 'Atomistic quantum transport simulation of nanoscale MOS devices' (matched: nano, atom)
- 'Atomistic Simulation Of Quantum Transport in Nanoelectronic Devices (With CD-ROM)' (matched: nano, atom)
- 'Atomistic simulations of electronic structure in realistically-sized wurtzite InN/GaN quantum dots having different geometries' (matched: atom, quantum dot, /GaN)
- 'Automated reaction mechanism generation : data collaboration, Heteroatom implementation, and model validation' (matched: atom)
- 'Bandwidth controlled quantum phase transition between an easy-plane quantum spin Hall state and an s-wave superconductor' (matched: superconduct)
- 'Baryon Number Transport, Strangeness Conservation and $\Omega$-hadron Correlations [arXiv]' (matched: baryon)
- 'Basic characteristics of neutrino flavor conversions in the post-shock regions of core-collapse supernova' (matched: supernov, neutrino)
- 'Bayesian inference of atomistic structure in functional materials' (matched: atom)
- 'Benchmarking Study of Ballistic Current Transport Equations in Symmetric Double-Gate nano-MOSFET by Using Numerical Calculations and Simulation' (matched: nano, mosfet)
- 'BGK subgrid model for neutrino quantum kinetics' (matched: neutrino)
- 'Bias-Independent Subthreshold Swing in Nanoscale Cold-Source Field-Effect Transistors by Drain Density-of-States Engineering [arXiv]' (matched: nano, transistor)
- 'Bias-Independent Subthreshold Swing in Nanoscale Cold-Source Field-Effect Transistors by Drain Density-of-States Engineering' (matched: nano, transistor)
- 'Biorthogonal polynomials related to quantum transport theory of disordered wires' (matched: bio)
- 'Bottom-up device simulations: Modeling electrical currents on the atomic scale' (matched: atom)
- 'Bridging first principles modelling with nanodevice TCAD simulations' (matched: nano)
- 'Cathodoluminescence of quantized energy states at AlGaN/GaN interface' (matched: AlGaN, Cathodo, /GaN, GaN/)
- 'Cavity-Induced Quantum Interference and Collective Interactions in van der Waals Systems' (matched: der Waals)
- 'Characteristics of inversion, accumulation and junctionless mode silicon N-type and P-type bulk FinFETs with optimized 3-nm nano-fin structure' (matched: nano, silicon)
- 'Charge and energy transport in 0D/2D systems probed using linear and nonlinear spectroscopy' (matched: spectroscop)
- 'Chemical Reaction of Ultracold Atoms and Ions in a Hybrid Trap' (matched: chemi,  ion, atom)
- 'Chiral detection of Majorana bound states at the edge of a quantum spin Hall insulator' (matched: majorana, chiral)
- 'Chiral transport along magnetic domain walls in the quantum anomalous Hall effect' (matched: chiral)
- 'Chirality-Driven Magnetization Emerges from Relativistic Four-Current Dynamics' (matched: chiral)
- 'Collaborative Routing in Partially-Trusted Relay based Quantum Key Distribution Optical Networks' (matched: optic)
- 'Combination of equilibrium and non-equilibrium carrier statistics into an atomistic quantum transport model for tunneling hetero-junctions [arXiv]' (matched: atom)
- 'Comment on "breakdown of interference rules in azulene, a nonalternant hydrocarbon" [arXiv]' (matched: hydrocarbo)
- 'Comment on "Zeeman-Driven Lifshitz Transition: A Model for the Experimentally Observed Fermi-Surface Reconstruction in YbRh_2Si_2" Reply' (matched: Fermi)
- 'Comparison of spontaneous emission in trapped ion multi-qubit gates at high magnetic fields [arXiv]' (matched:  ion)
- 'Competing correlated states around the zero-field Wigner crystallization transition of electrons in two dimensions' (matched: crystal)

,Title,Authors,Year,Journal,DOI,Publisher,ReferenceType,Database,Q,T,Abstract,year
0,10th EAI International Conference on Industria...,NaN,2024,Lecture Notes of the Institute for Computer Sc...,NaN,NaN,JOUR,Scopus,7,7,The proceedings contain 18 papers. The special...,2024.0
1,10th International Conference on Emerging Ubiq...,NaN,2019,Procedia Computer Science,NaN,NaN,CONF,Scopus,7,6,The proceedings contain 126 papers. The topics...,2019.0
2,10th International Conference on Monte Carlo a...,NaN,2013,Springer Proceedings in Mathematics and Statis...,NaN,NaN,CONF,Scopus,1,6,The proceedings contain 34 papers. The special...,2013.0
3,10th International Symposium on Intelligence C...,NaN,2019,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,1,6,The proceedings contain 32 papers. The special...,2019.0
4,11th Conference on Advanced Computer Architect...,NaN,2016,Communications in Computer and Information Sci...,NaN,NaN,JOUR,Scopus,1,5,The proceedings contain 17 papers. The special...,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4095,First-principles based ballistic transport sim...,"[Chang, P., Liu, X., Liu, F., Du, G.]",2019,Japanese Journal of Applied Physics,10.7567/1347-4065/aafb4f,NaN,JOUR,Scopus,1,5,Ballistic performance of monolayer and few-lay...,2019.0
4096,Routing protocol of fiber quantum communicatio...,"[Yuan, X.-H., Li, C.-W.]",2017,Kongzhi Lilun Yu Yingyong/Control Theory and A...,10.7641/CTA.2017.70652,NaN,JOUR,Scopus,1,6,A routing protocol is proposed for the fiber q...,2017.0
4097,Research on quantum cognition and decision mak...,"[Song, Q.-Y., Fu, W.-P., Wang, W., Gao, Z.-Q.,...",2022,Kongzhi Lilun Yu Yingyong/Control Theory and A...,10.7641/CTA.2021.00892,NaN,JOUR,Scopus,1,5,Autonomous vehicles will share roads with huma...,2022.0
4098,A clutter suppression method utilizing time de...,"[Zhai, Y., Wu, J., Wang, D.]",2015,Hsi-An Chiao Tung Ta Hsueh/Journal of Xi'an Ji...,10.7652/xjtuxb201512008,NaN,JOUR,Scopus,1,6,A novel clutter suppression method utilizing w...,2015.0
4099,Simulation of vehicle distribution path optimi...,"[Ding, Y.]",2021,Shenyang Gongye Daxue Xuebao/Journal of Shenya...,10.7688/j.issn.1000-1646.2021.03.13,NaN,JOUR,Scopus,1,6,In view of the problems of low load rate of si...,2021.0

In [10]:
#Optional: Export to Excel
#output_file = 'ArticlesToAnalize.xlsx'
#filtered_df.to_excel(output_file, index=False)

#print(f"DataFrame successfully written to {output_file}")